### ISSUE TITLE
"Also at" times are using the wrong date formatter time zone

### ISSUE THREAD

**Issue by chrisballinger** [iBurnApp/iBurn-Android#41]
![Screenshot_20230819-140842](https://github.com/iBurnApp/iBurn-Android/assets/518687/565201fd-a5ad-4f67-9227-3e86ef83b73d)

**Comment by OnlyInAmerica** [comment]
Thank you for opening. This is closed by https://github.com/iBurnApp/iBurn-Android/pull/42
